Document method parameters and return types
consolidation/robo pull request #1122
Opened 2022-08-21 11:56 UTC by Naktibalda

### Overview
This pull request:

- [x] Adds a feature
- [x] Has tests that cover changes

### Summary
A lot of redundant `@param` and `@return` annotation had been removed after declaring correct types in Codeception.

This change documents declared types of method parameters and return types.

### Description

Effect of this change can be seen at https://github.com/Codeception/codeception.github.com/pull/646

2022-08-23 21:27 UTC, DavertMik approved these changes

2022-08-23 21:28 UTC, DavertMik commented
This PR changes only GenMarkdownTask which we use internally in Codeception so I'm for this to be merged
@greg-1-anderson are you ok with that?

2022-08-24 03:28 UTC, greg-1-anderson commented on .gitignore
> +composer.lock
Robo does highest / lowest testing, which requires composer.lock be committed to the repository. Committing the composer.lock also allows the phar build to be reproducible.

2022-08-24 03:28 UTC, greg-1-anderson requested changes
Looks good for me, except composer.lock should not be added to the .gitignore.

2022-08-29 22:04 UTC, DavertMik commented
@greg-1-anderson can we merge it?

2022-09-08 08:30 UTC, DavertMik commented
@greg-1-anderson I'm merging it?

2022-09-11 15:20 UTC, Naktibalda commented
I made a small change to document parameters in correct order, when some parameters have `@param` annotations and others don't.

Effect can be seen in this commit: https://github.com/Codeception/codeception.github.com/commit/36b6d9891080afab38dcb14284b988c9614a3793

2022-09-12 16:24 UTC, greg-1-anderson commented
LGTM. Thanks.

2022-09-12 16:24 UTC, merged